services:
  web:
    build: .
    ports:
      - "8008:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://efactura_user:efactura_pass@db:5432/efactura_db
      - SECRET_KEY=${SECRET_KEY:-a6466c654a2eb9691c35de104208d66e2fe740728b73bae48d769355106e3092}
      - ANAF_API_BASE_URL=https://api.anaf.ro
      - FLASK_ENV=${FLASK_ENV:-production}
      - TZ=${TZ:-Europe/Bucharest}
    volumes:
      - invoice_data:/app/data
    command: gunicorn -w 4 -b 0.0.0.0:8000 "manage:app"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: efactura_user
      POSTGRES_PASSWORD: efactura_pass
      POSTGRES_DB: efactura_db
      TZ: ${TZ:-Europe/Bucharest}
      PGTZ: ${TZ:-Europe/Bucharest}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  invoice_data: